In [1]:
#!pip install tsp
#Dominik Jagoda
#Algorytmy Ewolucyjne Inżynieria Danych III rok

In [3]:
import tsp
import numpy as np
#import matplotlib.pyplot as plt
import time

In [4]:
#DANE
#https://dateandtime.info/pl/citycoordinates.php?id=3094802
#https://www.wspolrzedne-gps.pl

In [5]:
all_cit=np.array([
             [50.8703300,20.6275200],#Kielce
             [50.6826500,21.7489800],#Sandomierz
    [50.8520727,19.9667772],#Włoszczowa
    [50.6394435,20.3046116],#Jędrzejów
    [50.5201929,20.5256241],#Pinczów
    [50.46759,20.71919],#Busko-Zdrój
    [50.267489,20.4853308],#Kazimierza Wileka
    [50.5612276,21.1677849],#Staszów
    [50.8017661,21.4238281],#Opatów
    [50.9398768,21.38743],#Ostrowiec Świętokrzyski
    [51.0518865,21.0761377],#Starachowice
    [51.1138821,20.857883],#Skarżysko Kamienna
    [51.1910223,20.4071836],#Końskie
    [50.0614300,19.9365800],#Kraków
    [50.3566016,20.0276912],#Miechów
    [50.2788158,19.5596307],#Olkusz
    [50.1411926,19.4028502],#Chrzanów
    [50.0382443,19.2214053],#Oświęcim
    [49.8834484,19.4925345],#Wadowica
    [49.834608,19.9384283],#Myślenice
    [49.74079,19.5905975],#Sucha Beskidzka
    [49.4818229,20.030541],#Nowy targ
    [49.2969446,19.950659],#Zakopane
    [49.7061713,20.4217266],#Limanowa
    [49.6249173,20.691346],#Nowy Sacz
    [49.65829,21.1593832],#Gorlice
    [50.0123784,20.9880739],#Tarnow
    [49.9678396,20.6068496],#Brzesko
    [49.9693563,20.430541],#Bochnia
    [50.1743495,20.9850707],#Dąbrowa tarnowska
    [49.9823773,20.0602114],#Wieliczka
    [50.5653105,22.0644075],#Stalowa Wola
    [50.5715277,21.6704871],#Tarnobrzeg
    [50.5198985,22.139886],#Nisko
    [50.2892506,21.4243685],#Mielec
    [50.2433277,21.7754563],#Kolbuszowa
    [50.2621687,22.418892],#Leżajsk
    [50.1574473,23.1225859],#Lubaczów
    [50.0104958,22.678605],#Jarosław
    [50.0601735,22.4923769],#Przeworsk
    [50.0690725,22.2320924],#Łańcut
    [50.0528608,21.6116324],#Ropczyce
    [50.0514601,21.4104804],#Dębica
    [49.7470465,21.4743139],#Jasło
    [49.870208,21.7856291],#Strzyżów
    [49.6938045,21.7651458],#Krosno
    [49.6950395,22.0196537],#Brzozów
    [49.5609053,22.207028],#Sanok
    [49.7821562,22.7692634],#Przemyśl
    [49.4689014,22.3303816],#Lesko
    [49.4301874,22.5877003],#Ustrzyki Dolne
    [50.0413200,21.9990100]#Rzeszów
            
])

n=len(all_cit)

In [6]:
n

52

In [7]:
import math as m

In [8]:

def dist(i,j):
    R=6400
    if i == j:
        return 0
    else:
        return R*np.arccos((m.sin(all_cit[i,1]/180)*m.sin(all_cit[j,1]/180) +
               m.cos(all_cit[i,1]/180)*m.cos(all_cit[j,1]/180)*m.cos((all_cit[i,0]/180)-(all_cit[j,0]/180))))

In [9]:
dist(1,2)

63.64908168420394

In [10]:
all_cit[0]


array([50.87033, 20.62752])

In [11]:
#def all_dist(i,j): # funkcja odległości między wszystkimi miastami
    #return np.sqrt((all_cit[i,0]-all_cit[j,0])**2 + (all_cit[i,1]-all_cit[j,1])**2)

In [12]:
dt=[[dist(i,j) for i in range(n)] for j in range(n)]
np.round(np.array(dt),2)

array([[  0.  ,  40.42,  23.5 , ...,  78.19,  86.27,  56.87],
       [ 40.42,   0.  ,  63.65, ...,  47.56,  53.31,  24.32],
       [ 23.5 ,  63.65,   0.  , ...,  97.2 , 105.85,  77.72],
       ...,
       [ 78.19,  47.56,  97.2 , ...,   0.  ,   9.25,  23.38],
       [ 86.27,  53.31, 105.85, ...,   9.25,   0.  ,  30.05],
       [ 56.87,  24.32,  77.72, ...,  23.38,  30.05,   0.  ]])

In [13]:
# konwersja tablicy odległości do słownika (potrzebne dalej dla wołania f. bibliotecznej)
dis = {(i, j): dt[i][j] for i in range(n) for j in range(n)}

In [14]:
dis

{(0, 0): 0,
 (0, 1): 40.421058976689906,
 (0, 2): 23.50193056631973,
 (0, 3): 14.083420433339292,
 (0, 4): 12.887781523036873,
 (0, 5): 14.593929845232529,
 (0, 6): 21.8866274210338,
 (0, 7): 22.09451914982001,
 (0, 8): 28.416513827479655,
 (0, 9): 27.130412100144124,
 (0, 10): 17.191403797175443,
 (0, 11): 11.87792359362484,
 (0, 12): 13.773417932751839,
 (0, 13): 37.686274003712825,
 (0, 14): 28.004591173113408,
 (0, 15): 43.34182113380751,
 (0, 16): 50.5953052003859,
 (0, 17): 58.00104925123796,
 (0, 18): 53.33425609959617,
 (0, 19): 44.0372850770914,
 (0, 20): 54.33381867761673,
 (0, 21): 53.44990954403698,
 (0, 22): 60.573562157529324,
 (0, 23): 41.7694018480022,
 (0, 24): 44.04849282146377,
 (0, 25): 46.795948331126766,
 (0, 26): 32.90161350301856,
 (0, 27): 31.88675691525797,
 (0, 28): 32.58800204432155,
 (0, 29): 27.673735600954565,
 (0, 30): 37.29554904043743,
 (0, 31): 52.2119719048978,
 (0, 32): 38.55501297942579,
 (0, 33): 55.17790859288526,
 (0, 34): 34.98265466434478,
 (0

In [15]:
time0 = time.time()    # czas start
t_tsp = tsp.tsp(range(n),dis) # znajdź DOKŁADNE rozwiązanie
time1 = time.time()    # czas stop

print(t_tsp)
print("czas wykonania:",round(time1 - time0,1),"s")

(548.8637144475491, [0, 11, 10, 9, 8, 7, 34, 42, 41, 35, 32, 1, 31, 33, 51, 40, 36, 39, 38, 37, 48, 50, 49, 47, 46, 44, 45, 43, 25, 26, 29, 5, 4, 6, 28, 27, 24, 23, 30, 13, 19, 21, 22, 20, 18, 17, 16, 15, 14, 3, 2, 12])
czas wykonania: 125.6 s


In [16]:
p_tsp=np.array(t_tsp[1]) # najkrótsza trasa
t_tsp[0] # długość najkrótszej trasy

548.8637144475491

In [17]:
#Komórka ta powoduje zamknięcie trasy 
t=t_tsp[1]
index=0
route=np.insert(np.append(t,0),0,0)
route=np.delete(route,index)
tour=np.array([all_cit[i] for i in route])
tour


array([[50.87033  , 20.62752  ],
       [51.1138821, 20.857883 ],
       [51.0518865, 21.0761377],
       [50.9398768, 21.38743  ],
       [50.8017661, 21.4238281],
       [50.5612276, 21.1677849],
       [50.2892506, 21.4243685],
       [50.0514601, 21.4104804],
       [50.0528608, 21.6116324],
       [50.2433277, 21.7754563],
       [50.5715277, 21.6704871],
       [50.68265  , 21.74898  ],
       [50.5653105, 22.0644075],
       [50.5198985, 22.139886 ],
       [50.04132  , 21.99901  ],
       [50.0690725, 22.2320924],
       [50.2621687, 22.418892 ],
       [50.0601735, 22.4923769],
       [50.0104958, 22.678605 ],
       [50.1574473, 23.1225859],
       [49.7821562, 22.7692634],
       [49.4301874, 22.5877003],
       [49.4689014, 22.3303816],
       [49.5609053, 22.207028 ],
       [49.6950395, 22.0196537],
       [49.870208 , 21.7856291],
       [49.6938045, 21.7651458],
       [49.7470465, 21.4743139],
       [49.65829  , 21.1593832],
       [50.0123784, 20.9880739],
       [50

In [26]:

lenpa=np.round(t_tsp[0],3) # długość najkrótszej trasy
lenpa

548.864

In [20]:
#!pip install folium

In [21]:

import folium

In [22]:
my_map = folium.Map([50.0614300,19.9365800])
for i in tour:
    folium.Marker(i).add_to(my_map)
my_map

In [23]:
my_map = folium.Map([50.0614300,19.9365800])
for i in tour:
    folium.Marker(i).add_to(my_map)
    
folium.PolyLine(tour, color="red", weight=2.5, opacity=1).add_to(my_map)
my_map

In [24]:
my_map = folium.Map([50.0614300,19.9365800])
    
folium.PolyLine(tour, color="red", weight=2.5, opacity=1).add_to(my_map)
my_map